#!/bin/bash

set -Eeu -o pipefail

echo "iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +31.0°C  

k10temp-pci-00c3
Adapter: PCI adapter
Vcore:       688.00 mV 
Vsoc:          1.04 V  
Tctl:         +40.0°C  
Tdie:         +40.0°C  
Icore:        13.00 A  
Isoc:         13.75 A  

nvme-pci-0200
Adapter: PCI adapter
Composite:    +29.9°C  (low  =  -0.1°C, high = +85.8°C)
                       (crit = +86.8°C)
Sensor 1:     +29.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +32.9°C  (low  = -273.1°C, high = +65261.8°C)

thinkpad-isa-0000
Adapter: ISA adapter
fan1:           0 RPM
temp1:        +40.0°C  
temp2:         +0.0°C  
temp3:         +0.0°C  
temp4:         +0.0°C  
temp5:         +0.0°C  
temp6:         +0.0°C  
temp7:         +0.0°C  
temp8:            N/A  

amdgpu-pci-0600
Adapter: PCI adapter
vddgfx:           N/A  
vddnb:            N/A  
edge:         +40.0°C  (crit = +80.0°C, hyst =  +0.0°C)

BAT0-acpi-0
Adapter: ACPI interface
in0:          11.61 V
"