#!/bin/bash

VALUE_COLOR=${color:-$(xrescat i3xrocks.value.color)}
VALUE_FONT=${font:-$(xrescat i3xrocks.value.font)}

PANGO_START="<span color=\"${VALUE_COLOR}\" font_desc=\"${VALUE_FONT}\">"
PANGO_END="</span>"

gsettings get org.gnome.desktop.input-sources mru-sources | sed -r "s,\S*\s'([^']+).*,$PANGO_START\1$PANGO_END,"
gsettings monitor org.gnome.desktop.input-sources mru-sources | sed -u -r "s,\S*\s\S*\s'([^']+).*,$PANGO_START\1$PANGO_END,"
