#!/usr/bin/env bash

gsettings get org.gnome.desktop.input-sources mru-sources | sed -r "s/\S*\s'([^']+).*/\1/"
gsettings monitor org.gnome.desktop.input-sources mru-sources | sed -u -r "s/\S*\s\S*\s'([^']+).*/\1/"

