#!/bin/bash
#
# Copyright 2019 MerlinElMago 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#Variables
VALUE_COLOR=${color:-$(xrescat i3xrocks.value.color "#D8DEE9")}
LABEL_ICON=${label_icon:-$(xrescat i3xrocks.label.wifi )}
LABEL_COLOR=${label_color:-$(xrescat i3xrocks.label.color "#7B8394")}
VALUE_FONT=${font:-$(xrescat i3xrocks.value.font "Source Code Pro Medium 13")}

COLOR_ON="$VALUE_COLOR"
COLOR_OFF="$LABEL_COLOR"
TOGGLE_OFF=${label_on:-$(xrescat i3xrocks.label.off -)}
TOGGLE_ON=${label_on:-$(xrescat i3xrocks.label.off +)}
KB_MASK=`xset -q | grep -o "mask:[\ 0-9]*$" | cut -d" " -f 3`

#Set icon variables (can be overridden from the i3 config file)
[[ -z "$caps_icon" ]] && CAPS_ICON=$(xrescat i3xrocks.label.capslock C) || CAPS_ICON=$caps_icon
[[ -z "$num_icon" ]] && NUM_ICON=$(xrescat i3xrocks.label.numlock N) || NUM_ICON=$num_icon

#Print the lines
#Check the first bit of the mask (caps)
if [[ $((KB_MASK & 1)) == 1 ]];then
	echo -n "<span color=\"${LABEL_COLOR}\">${CAPS_ICON} </span> <span color=\"${COLOR_ON}\">${TOGGLE_ON} </span> "
else
	echo -n "<span color=\"${LABEL_COLOR}\">${CAPS_ICON} </span> <span color=\"${COLOR_OFF}\">${TOGGLE_OFF} </span> "
fi

#Now check the second bit of the mask (num)
if [[ $(((KB_MASK & 2) >> 1)) == 1 ]];then
	echo "<span color=\"${LABEL_COLOR}\">${NUM_ICON} </span> <span color=\"${COLOR_ON}\">${TOGGLE_ON} </span>"
else
	echo "<span color=\"${LABEL_COLOR}\">${NUM_ICON} </span> <span color=\"${COLOR_OFF}\">${TOGGLE_OFF} </span>"
fi
