#!/bin/bash

BUTTON=${button:-}
VALUE_COLOR=${color:-$(xrescat i3xrocks.value.color "#D8DEE9")}

LABEL_ICON=${label_icon:-$(xrescat i3xrocks.label.next-workspace-widget )}
LABEL_COLOR=${label_color:-$(xrescat i3xrocks.label.color "#7B8394")}
VALUE_FONT=${font:-$(xrescat i3xrocks.value.font "Source Code Pro Medium 13")}

echo "<span color=\"${LABEL_COLOR}\">${LABEL_ICON}</span><span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\"> </span>" # full text
echo "<span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\"> </span>" # short text

if [ "x${BUTTON}" == "x1" ]; then
    /usr/share/i3xrocks/next-workspace
fi

