#!/bin/bash

CONNECTION=$(nmcli -t connection show --active | awk -F ':' '
/wg0|tun0/{vpn="ON"} /wireguard|tun0|vpn/{name=$1}
END{if(vpn) printf("%s", name)}')

LABEL_COLOR=${vpn_label_color:-$(xrescat i3xrocks.vpn.label_color)}
VALUE_COLOR="${vpn_color:-$(xrescat i3xrocks.vpn.color)}"
VALUE_FONT=${font:-$(xrescat i3xrocks.value.font)}

if [[ -z "$CONNECTION" ]]; then
    exit 0
else
   echo "<span color=\"${LABEL_COLOR}\" font=\"FontAwesome\"> </span> <span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\">$CONNECTION</span>" # full text
   echo "<span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\">ON</span>" # short text
fi
