#!/bin/bash

# Depends on lm-sensors (https://packages.ubuntu.com/bionic/lm-sensors)

VALUE_FONT=${font:-$(xrescat i3xrocks.value.font "Source Code Pro Medium 13")}

TEMP=$(sensors -u | grep -Po 'temp1_input: \K\d*' | head -n 1)

if [[ ${TEMP} -gt 90 ]]
then
  COLOR=${critical_color:-$(xrescat i3xrocks.critical.color "#BF616A")}
elif [[ ${TEMP} -gt 70 ]]
then
  COLOR=${warning:-$(xrescat i3xrocks.warning "#EBCB8B")}
else
  COLOR=${color:-$(xrescat i3xrocks.value.color "#D8DEE9")}
fi

echo "<span font_desc=\"${VALUE_FONT}\" color=\"${COLOR}\">${TEMP}℃</span>"
