#!/bin/bash
LABEL_ICON=${icon:-$(xrescat i3xrocks.label.weather)}
LABEL_COLOR=${label_color:-$(xrescat i3xrocks.label.color "#7B8394")}
VALUE_COLOR=${color:-$(xrescat i3xrocks.value.color "#D8DEE9")}
VALUE_FONT=${font:-$(xrescat i3xrocks.value.font "Source Code Pro Medium 13")}

# Information on the various formats: https://github.com/chubin/wttr.in
VALUE_WEATHER_FORMAT=${weather_format:-$(xrescat i3xrocks.weather.format "1")}

# Defaults to IP address location
VALUE_WEATHER_LOCATION=${weather_location:-$(xrescat i3xrocks.weather.location "")}

WEATHER_ERROR_MESSAGE=${error_message:-$(xrescat i3xrocks.weather.error_message "")}
WEATHER_DATA_FILE=/tmp/i3xrocks_weather_data
RESPONSE_CODE=`curl -o ${WEATHER_DATA_FILE} -sS -w "%{http_code}" wttr.in/${VALUE_WEATHER_LOCATION}?format="${VALUE_WEATHER_FORMAT}"`

if [ $RESPONSE_CODE -ne "200" ]; then
    echo "${WEATHER_ERROR_MESSAGE}"
else
    WEATHER_DATA=`cat ${WEATHER_DATA_FILE}`
    echo "<span color=\"${LABEL_COLOR}\">$LABEL_ICON</span><span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\">${WEATHER_DATA}</span>"
fi

if [ ! -z "$button" ]; then
    /usr/bin/i3-msg -q exec xdg-open https://wttr.in/${VALUE_WEATHER_LOCATION}
fi
